version: "3"

services:
  db:
    image: registry.cn-shanghai.aliyuncs.com/goodat/teaching-open-db:latest
    container_name: teachingopen_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-teachingopen}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-teachingopen}
      - MYSQL_USER=${MYSQL_USER:-teachingopen}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-teachingopen}
    volumes:
      - ./data/mysql:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    restart: unless-stopped

  redis:
    image: registry.cn-shanghai.aliyuncs.com/goodathub/redis:6-alpine
    container_name: teachingopen_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    # ports:
    #   - "6379:6379"
    restart: unless-stopped

  api:
    image: registry.cn-shanghai.aliyuncs.com/goodat/teaching-open-api:latest
    container_name: teachingopen_api
    env_file:
      - ./.env
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data/upload:/opt/upFiles
    depends_on:
      - db
      - redis
    restart: unless-stopped

  web:
    image: registry.cn-shanghai.aliyuncs.com/goodat/teaching-open-web:latest
    container_name: teachingopen_web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped


