version: "3"

services:
  db:
    image: mysql:8.0
    container_name: teachingopen_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-teachingopen}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-teachingopen}
      - MYSQL_USER=${MYSQL_USER:-teachingopen}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-teachingopen}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: teachingopen_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    # build:
    #   context: ../api
    #   dockerfile: Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/goodat/teaching-open-api:latest
    env_file:
      - ./api.env
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
      - SPRING_PROFILES_ACTIVE=prod
      - ARGS=-spring.profiles.active=prod
    volumes:
      - ./data/upload:/opt/upFiles
    depends_on:
      - db
      - redis
    restart: unless-stopped

  web:
    # build:
    #   context: ../web
    #   dockerfile: Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/goodat/teaching-open-web:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped


